Add ccd shutterpages
hmcts/cnp-shutter-application pull request #3
Opened 2018-06-26 11:20 UTC by dwaynebailey

Adds for:

- ccd-case-management-web
- ccd-admin-web

I assume that's all.

Not 100% sure of the steps need to build this on aat.

2018-06-27 09:17 UTC, vlaurin requested changes
@dwaynebailey I believe we also need to shutter `ccd-api-gateway-web` as this is the one actually controlling access to the API for the Case Management Web. Given Case Management Web is a SPA running on the client side, if loaded before it's shuttered, the shutter won't affect it.

2018-06-29 15:29 UTC, dwaynebailey commented
@vlaurin added `ccd-api-gateway-web`, not sure if shuttering her this way is the correct way to shutter the API though?  Should we be doing it as an actual bit of JSON for the apps to be able to handle? IIUC how the gateway works.

2018-07-16 10:34 UTC, vlaurin commented
@dwaynebailey I agree this is not ideal. However, I think this pipeline is still relevant to trigger the shutter on the gateway. In order to return JSON, the change would have to be on the Traffic Manager for the gateway to redirect to or return JSON instead of the current HTML page.

2018-07-16 10:35 UTC, vlaurin approved these changes

2018-07-16 10:37 UTC, merged